services:
    redeye_stormpath.api_key_factory:
        class: Redeye\StormpathBundle\Factory\ApiKeyFactory
        public: false
        arguments:
            - "%redeye_stormpath.api_key.id_property_name%"
            - "%redeye_stormpath.api_key.secret_property_name%"

    redeye_stormpath.api_key:
        class: Stormpath\ApiKey
        public: false
        factory: ["@redeye_stormpath.api_key_factory", createFromFile]
        arguments:
            - "%redeye_stormpath.api_key.api_key_file%"

    redeye_stormpath.client:
        class: Stormpath\Client
        factory: [Redeye\StormpathBundle\Factory\ClientFactory, "createClient"]
        arguments:
            - "@redeye_stormpath.api_key"
            - ~  # Cache Manager
            - [] # Cache options

    redeye_stormpath.data_store:
        class: Stormpath\DataStore\DataStore
        factory: ["@redeye_stormpath.client", getDataStore]

    redeye_stormpath.tenant:
        class: Stormpath\Resource\Tenant
        factory: ~
        lazy: true

    redeye_stormpath.default_application.factory:
        class: Redeye\StormpathBundle\ApplicationFinder
        public: false
        arguments:
            - "@redeye_stormpath.data_store"
            - "@redeye_stormpath.tenant"

    redeye_stormpath.default_application:
        class: Stormpath\Resource\Application
        factory: ~
        lazy: true

    redeye_stormpath.resource_registry.group_href:
        class: Redeye\StormpathBundle\Registry\ResourceHrefRegistry

    redeye_stormpath.resource_registry.directory_href:
        class: Redeye\StormpathBundle\Registry\ResourceHrefRegistry

    stormpath_tenant:
        alias: redeye_stormpath.tenant

    stormpath_application:
        alias: redeye_stormpath.default_application
