services:
    redeye_stormpath.api_key_factory:
        class: Redeye\StormpathBundle\Factory\ApiKeyFactory
        public: false
        arguments:
            - %redeye_stormpath.api_key.id_property_name%
            - %redeye_stormpath.api_key.secret_property_name%

    redeye_stormpath.api_key:
        class: Stormpath\ApiKey
        public: false
        factory: [@redeye_stormpath.api_key_factory, createFromFile]
        arguments:
            - %redeye_stormpath.api_key.api_key_file%

    redeye_stormpath.guzzle_client:
        alias: redeye_stormpath.guzzle_client.default

    redeye_stormpath.guzzle_client.default:
        class: Guzzle\Http\Client
        tags:
            - { name: playbloom_guzzle.client }

    redeye_stormpath.request_executor:
        class: Stormpath\Http\HttpClientRequestExecutor
        public: false
        arguments:
            - @redeye_stormpath.guzzle_client

    redeye_stormpath.client_factory:
        class: Redeye\StormpathBundle\Factory\ClientFactory
        public: false
        arguments:
            - @redeye_stormpath.request_executor

    redeye_stormpath.client:
        class: Stormpath\Client
        factory: [@redeye_stormpath.client_factory, createClient]
        arguments:
            - @redeye_stormpath.api_key
            - %redeye_stormpath.client.cache_manager_class%
            - ~

    redeye_stormpath.data_store:
        class: Stormpath\DataStore\DataStore
        factory: [@redeye_stormpath.client, getDataStore]

    redeye_stormpath.tenant:
        class: Stormpath\Resource\Tenant
        factory: ~

    redeye_stormpath.default_application.factory:
        class: Redeye\StormpathBundle\ApplicationFinder
        public: false
        arguments:
            - @redeye_stormpath.data_store
            - @redeye_stormpath.tenant

    redeye_stormpath.default_application:
        class: Stormpath\Resource\Application
        factory: ~

    redeye_stormpath.id_site.url_builder:
        class: Redeye\StormpathBundle\IdSite\IdSiteUrlBuilder
        arguments:
            - @redeye_stormpath.api_key

    redeye_stormpath.id_site.callback_validator:
        class: Redeye\StormpathBundle\IdSite\IdSiteCallbackValidator
        arguments:
            - @redeye_stormpath.api_key
            - ~

    redeye_stormpath.id_site.token_store.stash:
        class: Redeye\StormpathBundle\TokenStore\StashTokenStore
        public: false
        arguments:
            - ~
    redeye_stormpath.resource_registry.group_href:
        class: Redeye\StormpathBundle\Registry\ResourceHrefRegistry

    redeye_stormpath.resource_registry.directory_href:
        class: Redeye\StormpathBundle\Registry\ResourceHrefRegistry

    stormpath_tenant:
        alias: redeye_stormpath.tenant

    stormpath_application:
        alias: redeye_stormpath.default_application
